# Site settings
title: Let me introduce my portfolio
description: Thank you for visiting
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://moduda1213.github.io/

# User settings
username: Better than YesterDay
user_description: 
user_title: 개발자 김철규입니다.
email: csjh1@naver.com
twitter_username: lorem_ipsum
github_username: https://github.com/moduda1213
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
